export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export const viewport = {
  width: 'device-width',
  initialScale: 1,
}

import './style.css'
import "@fortawesome/fontawesome-free/css/fontawesome.min.css";
import "@fortawesome/fontawesome-free/css/solid.min.css";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
